MPTCP Merge with v4.4
multipath-tcp/mptcp pull request #161
Opened 2017-01-16 06:17 UTC by cpaasch

2017-01-18 17:29 UTC, matttbe requested changes
Very good! Thank you a lot for the work! (and sorry again for the delay)

I just have 3 last comments, about details to maybe improve the readability.

2017-01-18 17:29 UTC, matttbe commented on net/mptcp/mptcp_ipv4.c
> +		goto discard;
(detail) could you move this goto into the `else` (or remove the else)?
But I guess it is because I am reading a diff but was strange to see the put not directly followed by the discard.

2017-01-18 17:29 UTC, matttbe commented on net/mptcp/mptcp_ipv4.c
> +		goto new_subflow;
is it not clearer to split the process of the join in the SYN or the final ACK? Because this label is used only once in the code and only the `reset` and `discard` labels are used by both conditions.

But it is already clearer than the previous version with `new_subflow_established` :-)

2017-01-18 17:29 UTC, matttbe commented on net/ipv4/tcp_ipv4.c
> +void tcp_copy_sk(struct sock *nsk, const struct sock *osk)
for maintaining purpose, could you add a comment here? (e.g. _Similar to: sock_copy_)

(and maybe an additional comment why we need an exception for (MP)TCP)

2017-01-25 00:59 UTC, cpaasch commented
Closing, as it has been pushed out.

2017-01-25 00:59 UTC, closed without merging