mptcp: fix sk_buff NULL pointer dereference in BLEST scheduler
multipath-tcp/mptcp pull request #357
Opened 2019-08-22 15:44 UTC by s6dlwebe

```blest_get_available_subflow``` uses ```skb->len``` together with the amount of
already inflight bytes on the choosen subflow to estimate the overall
available space in the send window.

This commit adds a check if ```skb``` is ```NULL``` so that we just assume 0 bytes
to add to the available space in that case. This will cause BLEST more
likely to detect a potential HoL-blocking situation where
```fast_bytes > avail_space``` trigger BLEST to return ```NULL``` instead of the
subflow choosen by the default scheduler.

Fixes: 4ffe6a4 (mptcp: BLocking ESTimation-based (BLEST) Scheduler)
Github-Fixes: #356 (Scheduler BLEST: Panic in 4.19.55)
Signed-off-by: Daniel Weber <weberdaniel@gmx.net>

2019-08-26 18:38 UTC, cpaasch requested changes
Uninitialized use of ```buffered_bytes```. I think you have to fix that.

2019-08-26 18:38 UTC, cpaasch commented on net/mptcp/mptcp_blest.c
> +		slow_bytes = buffered_bytes + slow_inflight_bytes; // bytes of this SKB plus those in flight already
If ```skb``` is NULL, ```buffered_bytes``` will be uninitialized. I guess that's not so good in the remainder of the function. You probably have to init it to 0 (?)

2019-09-09 09:37 UTC, s6dlwebe commented on net/mptcp/mptcp_blest.c
> +		slow_bytes = buffered_bytes + slow_inflight_bytes; // bytes of this SKB plus those in flight already
I'm not sure if I really have to. But does the compiler not initialize ```buffered_bytes``` implicitly to 0 as soon as it is declared? On the other hand you are right, initializing it explicitly doesn't hurt. I'm fixing this.

2019-09-10 16:41 UTC, cpaasch commented on net/mptcp/mptcp_blest.c
> +		slow_bytes = buffered_bytes + slow_inflight_bytes; // bytes of this SKB plus those in flight already
C does not initialize declared variables to 0. Thanks for fixing this!

2019-09-13 17:08 UTC, cpaasch approved these changes

2019-09-13 17:08 UTC, cpaasch commented
Merged into mptcp_trunk and mptcp_v0.95

2019-09-13 17:08 UTC, closed without merging